name: integrated_stroke
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_maps_flutter: ^2.5.3
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  camera: ^0.10.5+2
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.0.7
  geolocator: ^11.0.3
  flutter_map: ^6.1.0
  url_launcher: ^6.2.6
  file_picker: ^8.0.5
  video_player: ^2.8.6
  share_plus: ^10.0.4
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  http: ^1.6.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icons.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icons.png"